# Generated by Django 5.2 on 2025-04-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_dailyexpense_weeklyallowance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexpense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weeklyallowance',
            name='week_start_date',
        ),
        migrations.AlterField(
            model_name='dailyexpense',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
    ]
